version: "3.9"

services:
  bubblecloud:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bubblecloud
    ports:
      - "5923:5923"
    volumes:
      - bubblecloud-data:/app/app-files
    environment:
      - FLASK_ENV=production
    restart: always

  samba:
    image: dperson/samba
    container_name: samba
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - bubblecloud-data:/mount/files
    environment:
      - USER=admin;admin
      - SHARE=bubblecloud;/mount/files;yes;no;no;test
    restart: always
    network_mode: "host"

volumes:
  bubblecloud-data:
